const openingLines = [
  "La luna canta",
  "El río fluye",
  "El ave vuela",
  "Entre la bruma",
  "Curso del agua",
  "La flor se abre",
  "Luna llena hoy",
  "Montaña alta",
  "Canto de aves",
  "Río sereno",
  "Viento otoñal",
  "Brisa del agua",
  "Campo en calma",
  "Bosque antiguo",
  "Sendero viejo",
  "Hoja que cae",
  "Tierra húmeda",
  "Rocío frío",
  "La lluvia cae",
  "El mar respira",
  "Arde la tarde",
  "Cae la hoja",
  "Sopla el viento",
  "Suena un eco",
  "Late la tierra",
  "Vuelve la calma",
  "Nace el día",
  "Corre el tiempo",
  "Arde el cielo",
  "Canta el grillo",
];

export default openingLines;
