const middleLines = [
  "sobre viejas colinas",
  "en la noche serena",
  "bajo el cielo claro",
  "silencio de otoño",
  "sobre el lago azul",
  "noche llena de estrellas",
  "al viento lento se mece",
  "la bruma lenta se alza",
  "aves bailan muy alto",
  "crujen secas las ramas",
  "por el viejo sendero",
  "entre juncos lentos fluye",
  "con viento de otoño",
  "cuando canta el viento",
  "cuando cae la noche",
  "mientras duerme el valle",
  "entre hojas ya doradas",
  "cruza el cielo claro",
  "la tarde lenta se alarga",
  "cruza lento el río",
  "tiembla el aire frío",
  "se apaga la tarde",
  "el bosque aún respira",
  "el sol lento se inclina",
  "sus pasos ya se pierden",
  "la ciudad ya despierta",
  "luces solas en la calle",
  "una idea lenta nace",
  "un tren lejano se va",
  "papel y hondo silencio",
];

export default middleLines;
