const middleLines = [
  "sobre viejas colinas",
  "en la noche serena",
  "bajo el cielo claro",
  "silencio de otoño",
  "sobre el lago azul",
  "noche de mil luces",
  "se mece con el viento",
  "la bruma se eleva",
  "aves bailan muy alto",
  "crujen secas las ramas",
  "por el viejo sendero",
  "en juncos lentos fluye",
  "con viento de otoño",
  "cuando canta el viento",
  "cuando cae la noche",
  "mientras duerme el valle",
  "entre hojas doradas",
  "cruza el cielo claro",
  "la tarde se alarga",
  "cruza lento el río",
  "tiembla el aire frío",
  "se apaga la tarde",
  "el bosque aún vive",
  "el sol lento se inclina",
  "sus pasos ya se pierden",
  "la ciudad ya despierta",
  "luces solas sin calle",
  "una idea lenta nace",
  "un tren lejano se va",
  "papel y hondo eco",
];

export default middleLines;
