const closingLines = [
  "puro silencio",
  "como suspiro",
  "en la orilla",
  "día perfecto",
  "silencio y paz",
  "todo descansa",
  "queda la noche",
  "nada se mueve",
  "late la tierra",
  "queda el eco",
  "todo reposa",
  "todo se apaga",
  "la noche cae",
  "el mundo duerme",
  "nada urge ya",
  "el té ya frío",
  "llega la calma",
  "un gesto basta",
  "el día cede",
  "el pulso baja",
  "calla el valle",
  "duerme la luz",
  "se apaga el sol",
  "calma profunda",
  "todo en paz ya",
  "se va el rumor",
  "la voz se calma",
  "la noche sin fin",
  "todo ya pasó",
  "solo queda luz",
];

export default closingLines;
