const middles = [
  "sobre las colinas",
  "en la noche calma",
  "bajo el cielo claro",
  "silencio de otoño",
  "el río fluyendo",
  "sobre el lago azul",
  "noche de estrellas",
  "brilla luz dorada",
  "al viento se mece",
  "cima del monte",
  "la bruma se alza",
  "aves bailan alto",
  "susurra en piedras",
  "puente de madera",
  "el viento susurra",
  "vida en movimiento",
  "universo calmo",
  "naturaleza viva",
  "por este sendero",
  "entre juncos fluye",
  "pero la luciérnaga",
  "con viento de otoño",
  "flotando en el agua",
  "se despierta y ve",
];

export default middles;
