const verses = [
  "El sol brilla",
  "La luna canta",
  "El río fluye",
  "El ave vuela",
  "Luz de Luna, paz,",
  "Entre la niebla",
  "Río que murmura",
  "En la montaña",
  "La flor se abre",
  "Bajo nuestro sol",
  "En la rama",
  "Luna llena",
  "Cielo estrellado",
  "Las flores blancas",
  "Montaña alta",
  "Niebla en valle",
  "Canto de aves",
  "Riachuelo claro ",
  "Río sereno",
  "Viento otoñal",
  "La flor de loto",
];

export default verses;
