const verses = [
  "sobre las colinas",
  "en la noche serena",
  "bajo el cielo claro",
  "silencio de otoño",
  "el río fluyendo",
  "sobre el lago azul",
  "en la noche estrellada",
  "brilla con luz dorada",
  "al viento se mece",
  "en la cima del monte",
  "la bruma se alza",
  "aves danzan en el cielo",
  "susurra entre las piedras",
  "el puente de madera",
  "el viento susurra",
  "vida en movimiento",
  "universo en calma",
  "naturaleza viva",
  "por este camino",
  "entre juncos, fluyendo,",
  "pero la luciérnaga",
  "con viento de otoño",
  "flotando en el agua",
  "se despierta y mira",
];

export default verses;
